### ISSUE TITLE
Require commit SHA for latest-arm64 tag.

### ISSUE THREAD

**Issue by prajwalv-netapp** [GoogleContainerTools/distroless#1194]
Hi,

Currently, **distroless/static:latest-arm64** doesn't have commit SHA added as an additional tag. We always want to pin our base image to a certain hash to prevent breakage when there are changes in the image.

Alternatively, if we can get a manifest supporting both the architecture that would be helpful too.

![206086669-cd189aaa-d933-402b-bf80-60571ad19b54](https://user-images.githubusercontent.com/91181612/207505505-1c3c1547-f313-41a6-b22c-f22a62923309.png)

**Comment by dlorenc** [comment]
Shameless plug - feel free to try out the images at cgr.dev/chainguard/static - they should be roughly equivalent but the new build system handles multi-arch differently so you might not run into these problems.

**Comment by loosebazooka** [comment]
@prajwalv-netapp hrm.. yes only amd64 images are tagged by commit hash. But since tags are mutable by default, your safest option is to pin by manifest hash (not commit hash).

[gcr.io/distroless/static:latest](gcr.io/distroless/static:latest) is a multi arch image, you can pin to the manifest hash of the manifest-list (manifest supporting both images). This should pick the right image based on the underlying architecture.

```
FROM gcr.io/distroless/static@sha256:c3c3d0230d487c0ad3a0d87ad03ee02ea2ff0b3dcce91ca06a1019e07de05f12
```

**Comment by prajwalv-netapp** [comment]
@loosebazooka Thanks for pointing me to the multi-arch image, I can work with that.
