### ISSUE TITLE
RunAs unprivileged user

### ISSUE THREAD

**Issue by vic3lord** [GoogleContainerTools/distroless#235]
Is there a plan to support a non-root user inside base? Usually I'm using `nobody`

**Comment by mariusgrigoriu** [comment]
I believe it is already supported in the sense that you can run a Distroless-based image as some other user. Is your question that the image should default to a non-root user? If yes, then which UID is safe on all systems?

**Comment by vic3lord** [comment]
@mariusgrigoriu yes, I meant as a default value. I think something above 1000 is safe, unless there's something I am missing.

**Comment by mariusgrigoriu** [comment]
I've seen user accounts in the 5000s for GKE/COS. Other systems and their admins may decide on other UID ranges. Seems like a base image should be able to operate under any UID according to the sys admin's preferences.

**Comment by dlorenc** [comment]
I don't think we'll be changing the default of this from 0. Most other official images use 0, and it's easily overrideable in the runtime or in a base image.

**Comment by chanseokoh** [comment]
Opening for discussion from #306.

> Most other official images use 0,

I had a [similar argument](https://github.com/GoogleContainerTools/distroless/issues/306#issuecomment-466113438), but [@HazCod's argument](https://github.com/GoogleContainerTools/distroless/issues/306#issuecomment-476379259) was that those images keep the root mainly due to the existence of a package manager, which doesn't apply to Distroless.

In any case, if we do this, not sure if nobody would be a good fit, considering its nature. (Also nobody's home would be set to /nonexistent), so we may need to add a proper new user?

**Comment by briandealwis** [comment]
I'll add that we recommend avoiding running as root in our [_Best Practices for Operating Containers_](https://cloud.google.com/solutions/best-practices-for-operating-containers#avoid_running_as_root).

My only argument against using `nobody` is that the container user should have a home directory so that there's a place for dotfiles (e.g., `~/.docker/config.json`) to be installed.

**Comment by mattmoor** [comment]
I'd love to see us at a minimum publish `:nonroot` images, which consuming projects (e.g. ko, jib, bazel) can opt over to case-by-case.

cc @jonjohnsonjr Can you TAL?

**Comment by jonjohnsonjr** [comment]
The disastrous python2 -> python3 migration may be our industry's greatest blunder.

**Comment by pmorie** [comment]
I second @mattmoor's statements. Specific use case for me is publishing knative images that don't take root privs. Currently it appears that `ko` will have to inherit this from the base image.

**Comment by chanseokoh** [comment]
FTR, now the images have a user and a group all named "nonroot".

`/etc/passwd` content:
```
root:x:0:0:root:/root:/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/sbin/nologin
nonroot:x:65532:65532:nonroot:/home/nonroot:/sbin/nologin
```

`/etc/group` content:
```
root:x:0:
nobody:x:65534:
tty:x:5:
staff:x:50:
nonroot:x:65532:
```

**Comment by loosebazooka** [comment]
This doesn't apply to the language builds yet, does it?

**Comment by chanseokoh** [comment]
@loosebazooka all the images have the `nonroot` user and group. By default, all the images without the tag `:nonroot` run as root as usual. It is just that only the images with the `:nonroot` tag run as the `nonroot` user by default. And so far, only a small number of repositories introduced the `:nonroot` tag.
