### ISSUE TITLE
https://snapshot.debian.org/ is always down

### ISSUE THREAD

**Issue by elig** [GoogleContainerTools/distroless#269]
Hi,
I am just starting to play with the project, trying to do bazel build but https://snapshot.debian.org/ is mostly down and returning 503 Service Unavailable, I proxied it via my artifactory and managed to cache most packages but still.. any idea what is going on with this repo? why are you depending on the snapshot repo? is there other mirror I can use?

Thanks

**Comment by elig** [comment]
OK solved it by referencing to other official repos

**Comment by jo2y** [comment]
I would reopen this issue if I could.

The reason to use snapshot.debian.org is so that your build is hermetic. snapshot can be pinned to a specific point in time and won't change unless you take action. You can be sure that building today will match building next week, and can be rolled back to a working state if needed. If you're just experimenting, then using the main repositories is probably good enough. You'll run into small annoyances like the sha256 of Packages.gz will change unexpectedly as new updates are released to debian.

I started seeing this problem about 4 days ago. Given the timing of this mailing list thread, I wonder if bazel is triggering a rate limit. https://lists.debian.org/debian-snapshot/2018/12/msg00004.html
