### ISSUE TITLE
is there a reasonable way to expose dpkg_src targets for use in other projects?

### ISSUE THREAD

**Issue by tmc** [GoogleContainerTools/distroless#270]
As a user of rules_docker I'd like to include additional packages and being able to load() the dpkg_src's that distroless builds upon would lower maintenance burden and prevent packages being installed from different debian package lists.

**Comment by donmccasland** [comment]
distroless images do not include a package manager.  any package management steps need to be handled in either a multistage build or by forking and adding bazel rules.

**Comment by jonjohnsonjr** [comment]
I think this was closed prematurely? The issue seems to be asking about distroless's use of https://github.com/GoogleContainerTools/distroless/tree/master/package_manager and just having distroless expose targets for the packages each image depends on... is that right? How hard would that be, just reorganizing the build rules a bit?
