### ISSUE TITLE
sort files by name for reproducibility, compression, and diff

### ISSUE THREAD

**Issue by wmark** [GoogleContainerTools/distroless#274]
It's been claimed in a separate issue that an [aspirational goal were reproducibility](https://github.com/GoogleContainerTools/distroless/issues/242#issuecomment-431363053) (my words).

For that, please sort contents within layers by name. For example, with *tar* you'd `tar --sort=name`.

 * As side-effect it will be easier to use *git* and tools to spot changes in the image(s).  
For example, [using git's diff hooks](https://github.com/Blitznote/apt-image#hints).
 * Furthermore, files will lend itself to *delta encoding*.

**Comment by chanseokoh** [comment]
> For that, please sort contents of within layers by name.

That's an interesting point, but I guess it may not that simple. This will depend on how exactly `container_image` builds up a tar layer, but tar allows having an infinite number of files with the same name, so the order of addition should be preserved among the entries with the same name after sorting. But probably it would be best if `container_image` just replaces an old entry with a new entry so that the tar layer never has entries with the same name.

**Comment by donmccasland** [comment]
tools like container_diff are not confused by tar's antics.

**Comment by chanseokoh** [comment]
I think this issue still stands, much like https://github.com/bazelbuild/rules_docker/issues/675. That is, no matter where you run the Bazel build, you always get the exact same tarball by ensuring the order of the files in it. It is good to strive for reproducibility. The tooling isn't really the concern here.
