### ISSUE TITLE
Add *_VERSION flags for distroless images

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/distroless#301]
As per #291 we should add *_VERSION flags to the other distroless images too.

#276

**Comment by briandealwis** [comment]
The `openjdk` docker image also exposes `JAVA_DEBIAN_VERSION` too.

**Comment by markmsmith** [comment]
I really like the idea of this project, but lack of proper tagging of versions was one of the major points against using it in a recent assessment of base image options for Node containers at our company.

When tagging the versions, it would be really helpful if it was something like `V8` or `VERSION_8.1.2`, rather than just the number.  For example, if you go [here](https://console.cloud.google.com/gcr/images/distroless/GLOBAL/java?gcrImageListsize=30) and attempt to search for java 8 by entering `8` in the filter at the top, you get all the images that have 8 somewhere in their sha, not just ones with that tag.  As the list of images gets larger, it becomes less practical to find things this way.  If the tag had some text, you could do a much more specific search.  Maybe I'm just missing a trick to search more specifically there though.

Lastly, it would be nice to include tags with the full release SemVer, for when you're looking to base off of the sha of a specific node release (eg 10.15.3), not just "latest", or "some version of 10".

Thanks!

**Comment by donmccasland** [comment]
related to this conversation:
https://groups.google.com/g/distroless-users/c/Uufl6cxWgMI

**Comment by markmsmith** [comment]
@donmccasland Sorry, that url gives me a 404 and I can't find a public google group named `distroless-users`.  Is this a google-internal discussion?

**Comment by markmsmith** [comment]
I see this was closed. What was the conclusion? Are there plans to add tags with the full version (eg 1.2.3) and not just the major version?

**Comment by loosebazooka** [comment]
Probably not. Distroless will just stay at the latest version available from debian.
