### ISSUE TITLE
Eclipse OpenJ9

### ISSUE THREAD

**Issue by mkarg** [GoogleContainerTools/distroless#345]
Eclipse claims that OpenJ9 is better suited for container use than Hot Spot. In particular OpenJ9 has a shorter time to full performance, needs less RAM, and shares classes among container instances. It might be a good idea to provide a distroless image based on AdoptOpenJDK + OpenJ9.

**Comment by asad-awadia** [comment]
Is this going to happen?

**Comment by chanseokoh** [comment]
I do not think Distorless will use OpenJ9. (Personally, I find it weird that they call it "OpenJDK" when they swap out the OpenJDK JVM and replace it with IBM's JVM.) And it is even unclear if Distroless should use AdoptOpenJDK. For one, AdoptOpenJDK is not JCK/ TCK certified/compliant. Sure, I have read countless arguments that JCK/TCK may not be meaningful to some people, but all other freely available alternative OpenJDK builds that we can choose from are compliant.

**Comment by asad-awadia** [comment]
@chanseokoh what jdk/jre/jvm is/are used in the distroless image?

Feels like a black box and would be nice to see what’s in it

**Comment by chanseokoh** [comment]
Everything including openjdk are Debian packages. The package is `openjdk-8/11-jre-headless`.

**Comment by itelleria** [comment]
@chanseokoh As far as I know, the OpenJDK binary distributions that pass TCK compliance testing are:

- Red Hat's OpenJDK
- Azul's OpenJDK
- Amazon Correto
- Oracle's OpenJDK

Maybe I'm wrong but I haven't found a reference that confirms Debian's OpenJDK package is TCK certified.

**Comment by chanseokoh** [comment]
@itelleria yeah, so we are leaning towards one of the TCK certified builds, such as Azul’s.

**Comment by itelleria** [comment]
Thanks for your answer @chanseokoh 

Could you share why you are considering a TCK compliant OpenJDK instead of Debian's OpenJDK? Apart from having more guarantee that binaries meet the Java specification, I wonder if there are other reasons such as longer support of Java versions for example.

Additionally, recently AdoptOpenJDK has moved to Eclipse Foundation as [Eclipse Adoptium](https://projects.eclipse.org/projects/adoptium) project and it seems [Eclipse Adoptium will distribute only TCK compliant binaries](https://github.com/AdoptOpenJDK/openjdk-docker/issues/394#issuecomment-688622988). Surely you knew this. Maybe it's worth taking a look at it.

**Comment by chanseokoh** [comment]
Debian doesn't ship Java 8. That is the primary reason.

And thanks for the Adoptium link. Was not following the Adoptium closely.

**Comment by bilak** [comment]
Hello, anything new regarding this? I can see openj9 being adopted by AdoptOpenJDK.

**Comment by previousdeveloper** [comment]
Is this going to happen?
