### ISSUE TITLE
I build a image , but happen a error , help me please

### ISSUE THREAD

**Issue by YuaXan** [GoogleContainerTools/distroless#351]
Dockerfile:
FROM shadowsocks/shadowsocks-libev AS build
ADD . /app
WORKDIR /app
RUN ss-server -p 8388 -k password -m aes-256-gcm -u &

FROM gcr.io/distroless/base
COPY --from=build /app /app
WORKDIR /app
CMD ["/app"]

Display of run before:
root@www:~# docker run -it ss-test
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/app\": permission denied": unknown.

**Comment by chanseokoh** [comment]
This is because "/app" is a directory and not something you can execute. Take a look at [`ENTRYPOINT`](https://docs.docker.com/engine/reference/#entrypoint) and [`CMD`](https://docs.docker.com/engine/reference/builder/#cmd) references to understand how you can set them up to execute something you want. Perhaps `ss-server` is the executable that you want to run? I don't know anything about what `ss-server` does, but it seems like running it with `RUN` as a background process in the first `build` step seems not right.

Since this is unrelated to Distroless, I'll close it.
