### ISSUE TITLE
Upgrade to python 3.7.3 and close several CVEs.

### ISSUE THREAD

**Issue by kalexmills** [GoogleContainerTools/distroless#364]
List of CVEs below, from a scan of the base python 3 image:

```
CVE-2019-9636     python      3.5.3      critical                       9.8
CVE-2018-20060    urllib3     1.21.1     critical                       9.8
CVE-2018-18074    requests    2.16.0     critical                       9.8
CVE-2019-9636     python      3.5.3      critical                       9.8
CVE-2018-1060     python      3.5.3      high                           7.5
CVE-2018-20406    python      3.5.3      high                           7.5
CVE-2017-17522    python      3.5.3      high                           8.8
CVE-2018-1061     python      3.5.3      high                           7.5
CVE-2018-14647    python      3.5.3      high                           7.5
CVE-2017-17522    python      3.5.3      high                           8.8
CVE-2019-11324    urllib3     1.21.1     high        fixed in 1.24.2    7.5
CVE-2018-14647    python      3.5.3      high                           7.5
CVE-2018-1061     python      3.5.3      high                           7.5
CVE-2018-20406    python      3.5.3      high                           7.5
CVE-2018-1060     python      3.5.3      high                           7.5
CVE-2017-18207    python      3.5.3      medium                         6.5
CVE-2019-9947     python      3.5.3      medium                         6.1
CVE-2019-9740     python      3.5.3      medium                         6.1
CVE-2019-9947     python      3.5.3      medium                         6.1
CVE-2017-18207    python      3.5.3      medium                         6.5
CVE-2019-9740     python      3.5.3      medium                         6.1
```

If the maintainers are worried about breaking downstreams by upgrading to 3.7.3, creating additional tags on GCR for specific versions would be a good workaround.

**Comment by badbeeker** [comment]
Seems like distroless is tied to debian stretch packages.  Currently, python 3.5 is the default python for Debian Stretch so I'm guessing that the distroless base would need to follow debian "buster" in order for python 3.7.3 to be installed.  Is there an easy way to switch distroless to debian "buster" packages for the python image?

**Comment by kalexmills** [comment]
Looks like #137 is related. That issue was closed though, having determined that including packages from buster (and potentially sid?) would ultimately yield non-deterministic builds.

**Comment by MarkusTeufelberger** [comment]
The problem with #137 would be that packages from 2 distros would be mixed together. Maybe the tooling in distroless has improved since then, but back then the only thing that determined which files would end up in a container were the generated `Packages.json` files - and this PR would have mixed several ones from different distributions.

The result might be deterministic, but it definitely wouldn't be what you'd expect...

**Comment by aaliddell** [comment]
Might it be worth keeping this open to track of desire to move to a more recent python version? Whilst the proposed PR solution wasn't suitable, the underlying issue that 3.5 has a number of security issues still remains (and is missing some desirable features). I expect some CVEs listed above will probably have fixes backported to 3.5, but likely not everything.

The next steps would be to consider alternative fixes. Here's some starter ideas of varying suitability:

1. Build python from source on top of the existing stretch base
  - Pros: 
    - Can lock to any version and track security fixes
    - Generally it's quite simple to build python
  - Cons:
    - Additional complexity
    - Python build is not presently integrated with bazel (although there's desire elsewhere for rules that will build a local python interpreter)
    - Discarding the work of the distro package maintainers
    - Requires distroless maintainers to track python releases as well as the current Debian releases
2. Wait for Debian Buster
  - Pros:
    - Consistent with other lang images
    - Simplest solution
  - Cons:
    - Non-backported security issues above remain until Buster release date
    - This same issue will be hit during Buster lifecycle when 3.7 gets superseded 
3. Move to a different base, such as some Ubuntu derivative
  - Pros:
    - More frequent update cycle with LTS available
    - More up-to-date python versions available
    - Still dpkg based
  - Cons:
    - Inconsistent base from other lang images unless all are moved, which seems unreasonable
    - Significant rework to setup base packages

Personally, if it's feasible 1. would my preference (followed by 2), as we'll hit this exact same issue down the line due to Buster being frozen to 3.7. This method has some precedence, as the dotnet and nodejs lang images are not based on the Debian packages but sourced directly from upstream. However, these other langs use prebuilt binaries rather than build, but unfortunatly python does not distribute Linux binaries.

**Comment by MarkusTeufelberger** [comment]
In general I find it a bit ironic that a project called `distroless` is quite a bit behind on versions because the distro it uses underneath doesn't update that often. ;-)

Option 3 might not be THAT much work actually, the main issue you will run into is that I'm not aware of a historic archive mirror of all Ubuntu packages - this means that there is some risk that builds will break over time because the `.deb` files are no longer available (the one for Debian is also just best-effort by the way). There was a proposal a while back for having "lock-files" for Bazel which would at least make updating the packages much faster/easier, but I'm not sure if this is actively being implemented.

**Comment by kalexmills** [comment]
In #353 it's suggested to build distroless/base images wholly based on Debian stable/sid. I'm not an expert in Debian package management, but wouldn't using this approach avoid the issue with packages from two distros in the same image as mentioned by @MarkusTeufelberger?

**Comment by kalexmills** [comment]
In #353 it's suggested to build distroless/base images wholly based on Debian stable/sid. I'm not an expert in Debian package management, but wouldn't using this approach avoid the issue with packages from two distros in the same image as mentioned by @MarkusTeufelberger?

**Comment by kalexmills** [comment]
In #353 it's suggested to build distroless/base images wholly based on Debian stable/sid. I'm not an expert in Debian package management, but wouldn't using this approach avoid the issue with packages from two distros in the same image as mentioned by @MarkusTeufelberger?

**Comment by aaliddell** [comment]
It'd avoid the multiple distros issue, but Sid comes with its own set of issues:
- Packages have no stability or compatibility guarantees, by the very nature of being the 'unstable' branch. Following from this, getting a stable system of packages to work together from Sid is complicated.
- Security updates are not applied to Sid packages by the Debian Security Team, so we still end up with open CVEs until the maintainer patches them. See https://wiki.debian.org/Teams/Security: "The security team evaluates security threats, and produces updated packages for our stable and old-stable releases"

**Comment by kalexmills** [comment]
It seems like building python from source might be the best bet, then. From what I gather, the other images built from this repository do not do this, so it would be a different approach.

Are the distroless maintainers interested in going with/supporting this route?

**Comment by aaliddell** [comment]
FYI Buster is out: https://www.debian.org/News/2019/20190706

**Comment by JoostvDoorn** [comment]
Is it feasible to update all the distroless images to buster? This seems to be a good short term solution.

**Comment by kalexmills** [comment]
#371 seems to indicate that it is feasible indeed.
