### ISSUE TITLE
ARM version?

### ISSUE THREAD

**Issue by yegle** [GoogleContainerTools/distroless#377]
I've switched all my images to use distroless as base image and realize distroless doesn't have ARM version. Would it be possible to provide an ARM version?

I'm thinking about using my images on a RasPi3 so it would be great if ARMv7 (Debian armhf) is provided.

**Comment by avinashkurup** [comment]
I too am interested to know if ARMv8 support is provided for distroless. Plz let us know about this.

**Comment by wenyuangui** [comment]
any suggestion for arm64 version distroless image, or choose another base image which support arm64?

**Comment by mattmoor** [comment]
If you look at the linked issue, I have a tiny little Go program that can produce a fat Go image for amd64/arm64 with `distroless/static:nonroot` (since it's just data).

If that's all your are looking for, you could try running it to produce your own.  I'm using this with github.com/google/ko to run github.com/knative on a RPi4.

**Comment by mattmoor** [comment]
Alright, the linked issue now solves this for realz with proper arm64 packages.

**Comment by morlay** [comment]
@mattmoor  
could you try this https://github.com/discolix/discolix

**Comment by mattmoor** [comment]
@morlay @emacski Has any effort been made to upstream that work?

It sort of looks like a divergent fork without any preserved history, so hard to tell what's changed.  It has also shed some of the stuff this is still supporting (like debian stretch, and java).  I think we're also going to want Power and s390x to support Kubernetes multi-arch using these images.

What is it about discolix that we should try to do upstream that we are not?

**Comment by emacski** [comment]
I haven't made any effort. While I based discolix on this project, it is definitely not a fork. Additionally, I have only focused on supporting my own multi-arch projects thus far (i.e. I don't use a lot of java).

**Comment by mattmoor** [comment]
Alright, there are now tags for `:latest-arm64` and `:nonroot-arm64`.

**Comment by patoarvizu** [comment]
Was support for `arm/v7` dropped? I have a couple of builds that are using `FROM gcr.io/distroless/static:nonroot` building multi-arch (on an AMD machine) with `docker buildx build --platform=linux/arm/v7 ...` and they started failing today.

I guess it would be relatively safe to run the distroless amd64 image or an arm/v7 machine, but I'd like to know if the support is officially dropped and I need to find a permanent solution or if this was unintentional and I only need to find a temporary workaround.

**Comment by mattmoor** [comment]
It wasn't officially supported before, but as you obviously saw you could abuse the existing images for that purpose.

You should be able to get the same behavior you had previously by simply referencing either `gcr.io/distroless/static:nonroot-{arm64,amd64}`, but part of the refactoring I've been doing has been aimed at making it easier to add more architectures.

**Comment by mattmoor** [comment]
@patoarvizu LMK if `FROM gcr.io/distroless/static:nonroot-arm64` works or is still broken.  That shouldn't be a manifest list, so it should be very similar to what you were doing before, but actually an arm image (albeit 64-bit).

If you want to take a crack at adding arm/v7 you should join us in `#distroless` on K8s slack, and we can coordinate because we have some more changes coming to support non-static on arm64, and trying to get some testing for non-amd64 images presubmit.

**Comment by patoarvizu** [comment]
Oh thanks for the quick reply! I edited my original comment, I don't know if you saw the edit but yes, I realize it wasn't explicitly/officially supported before.

I'm running my builds right now using the suffix so I'll report back with the results.

It looks like until today, `nonroot` was a tag on [sha256:d0f414c64bdb0ceebea651b14ad5be9a281a7a1d67751f9de419316390239b62](https://console.cloud.google.com/gcr/images/distroless/GLOBAL/static@sha256:d0f414c64bdb0ceebea651b14ad5be9a281a7a1d67751f9de419316390239b62), which is a manifest (not a manifest list) and I assume it was amd64. If that's correct then both my amd and arm images have always been running on that amd layer, which means that running with `FROM gcr.io/distroless/static:nonroot-amd64` will probably work ok.

I have a Raspberry Pi Kubernetes homelab, so I'll be able to test right away 🙂

**Comment by mattmoor** [comment]
@patoarvizu I've been using the amd64 `static:nonroot` as a base image for running on an RPi4 K3s cluster without any issues, and using the same to test the new multi-arch images.  I've also been testing on a Graviton EKS cluster.

LMK if you hit any problems, but hopefully that unblocks you.

**Comment by patoarvizu** [comment]
Everything looks good! 👍

**Comment by morlay** [comment]
@mattmoor 

When DISTRO_SUFFIXES version could be published too? `static-debian10` `cc-debian10`

**Comment by mattmoor** [comment]
I think it'd be fine to add more variants to what we publish (they are all generated in BUILD), the problem is just that `cloudbuild.yaml` is the fully unrolled loop and is getting a bit unwieldy.

I think that if we adopted a simple bash loop for the expanded flavors we want `{variant}_{user}_{arch}_{distro}` and then had one-off logic to tag the "short names" from these and publish those as well, then it would be much simpler and less error prone.

This may require us to be even more regular in our build target naming than even what I've done, but I think it's a worthy cleanup.

**Comment by morlay** [comment]
Could we change the name of contrainer_image in bazel like 
`{group}_{distro}__{tag}_{arch}`, 
the double `_` could split for final image name & tag like `{group}-{distro}:{tag}-{arch}`

Which could be easier to convert image tag by single shell for all images.

```
//base:static_root_amd64_debian10 => //base:static_debian10__root_amd64  => static-debian10:root-amd64
//base:static_nonroot_amd64_debian10 => //base:static_debian10__nonroot_amd64  => tag static-debian10:nonroot-amd64

//nodejs:nodejs10_amd64_debian10  => //nodejs:nodejs_debian10__10_amd64  => nodejs-debian10:10-amd64
```

**Comment by mattmoor** [comment]
I would rather replicate the loops and format strings than parse the strings...

**Comment by morlay** [comment]
I parse the short name to make it simple in CI

```
      - run: ../hack/build.sh base/base
      - run: ../hack/build.sh base/base:nonroot

      - run: ../hack/build.sh base/debug
      - run: ../hack/build.sh base/debug:nonroot

      - run: ../hack/build.sh base/static
      - run: ../hack/build.sh base/static:nonroot

      - run: ../hack/build.sh cc/cc
      - run: ../hack/build.sh cc/cc:nonroot

      - run: ../hack/build.sh cc/debug
      - run: ../hack/build.sh cc/debug:nonroot
```
via: https://github.com/querycap/distroless/blob/master/.github/workflows/publish-base.yaml


It could be fine to clarify image tag

but at least the `_{arch}` in bazel name may need to be the suffix (as `{lang, debug} x {root, nonroot} x {debian flavor} x {arch}` https://github.com/GoogleContainerTools/distroless/issues/609)

then we could use the simple shell to build multi arch image in ci
```
- run: ../hack/build.sh base:static_root_debian10 static-debian10:latest
```

instead of

```
- run: ../hack/build.sh base:static_root_amd64_debian10 static-debian10:latest-amd64
- run: ../hack/build.sh base:static_root_arm64_debian10 static-debian10:latest-arm64
- run: ../hack/create.sh static-debian10:latest static-debian10:latest-amd64 static-debian10:latest-arm64
```

**Comment by morlay** [comment]
https://github.com/GoogleContainerTools/distroless/pull/616

I setup a matrix builds by github workflow

and prefer use the simple script `USER=${{ matrix.user }} DISTRO=${{ matrix.distro }} ./hack/build.sh ${{ matrix.target }}` for all builds
as the draft pr show

@mattmoor i have no idea to avoid to parse string

**Comment by chanseokoh** [comment]
> @mattmoor i have no idea to avoid to parse string

@morlay the repo uses Google Container Builder to build and publish images. If you see [`cloudbuild.yaml`](https://github.com/GoogleContainerTools/distroless/blob/e52e560310a03432eab208f339e73bdfd701a6b6/cloudbuild.yaml#L1), it's fully unrolled repetitions of `docker` commands with no loop. So, I believe what @mattmoor suggests by

> I would rather replicate the loops and format strings than parse the strings...

is along the line of

```sh
for lang in $LANG; do
  for user in $USER; do
    for version in $DEBIAN_VERSION; do
      for arch in $ARCH; do
        target=${lang}:${lang}_${user}_${version}_${arch}
        image=gcr.io/distroless/${lang}:${lang}-${user}-${version}-${arch}
        bazel run //${target}
        bazel tag bazel/${target} ${image}
        bazel push ${image}
      done
    done
  done
done
```

That is, format the Bazel target and image reference strings directly rather than trying to re-construct a target or an image ref by employing some logic to parse the other string.

**Comment by morlay** [comment]
`gcr.io/distroless/​${lang}​:​${lang}​-​${user}​-​${version}​-​${arch}​` 

means the image format will be changed in future？

**Comment by chanseokoh** [comment]
@morlay see https://github.com/GoogleContainerTools/distroless/issues/377#issuecomment-706570599:

> I think that if we adopted a simple bash loop for the expanded flavors we want {variant}_{user}_{arch}_{distro} and then had one-off logic to tag the "short names" from these and publish those as well,

I don't mean removing existing "short names." They will be there to stay. I expect there will be many new short names (automatically generated too) going forward. But at the same time, it makes sense to always have full names.

**Comment by morlay** [comment]
> it makes sense to always have full names

This will be better.

we could just alias image after the fullname image built.

hope the final rule be defined asap.

**Comment by timja** [comment]
Were the java images missed because they are in a different cloudbuild file?
https://github.com/GoogleContainerTools/distroless/blob/e52e560310a03432eab208f339e73bdfd701a6b6/java/cloudbuild.yaml
