### ISSUE TITLE
Add libc++ to distroless/cc

### ISSUE THREAD

**Issue by PiotrSikora** [GoogleContainerTools/distroless#394]
Please consider adding libc++ to `distroless/cc`, to allow dynamic linking against libc++ instead of GNU libstdc++.

Official packages are available for Debian Stretch (`distroless`'s base) on LLVM's website:
https://apt.llvm.org/

**Comment by evanj** [comment]
I would argue this should be a *separate* image, since it is effectively a different runtime (`distroless/clang++`?). Now that we have Debian10, we could easily add libc++ from Debian10: https://packages.debian.org/buster/libc++1-7 ; this is almost certainly older than the "latest" LLVM release, but would have a clear build story: Build stuff with Debian10, package it into a Distroless image.

**Comment by PiotrSikora** [comment]
Separate image could also work, but it probably should be named `distroless/libcxx`, since it has nothing to do with the compiler. Note that we need definitely a recent version than 7.0.1, but we could install that either from the official release tarball or apt.llvm.org.

@kyessenov any chance you want to add that?
