### ISSUE TITLE
Document nonroot and nobody user/group

### ISSUE THREAD

**Issue by alexbrand** [GoogleContainerTools/distroless#443]
While looking to adopt distroless for an application, I wanted to know how to run my application as a non root user. It took me a while to discover that there is a `nonroot` and `nobody` uid/gid in the images.

Document the availability of `nonroot` and `nobody`. Also document the differences between them, and when they should be used.

**Comment by eugenebnd** [comment]
It takes quite some time to get the UIDs
```
Status: Downloaded newer image for gcr.io/distroless/base-debian10:debug
# cat /etc/passwd
root:x:0:0:root:/root:/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/sbin/nologin
nonroot:x:65532:65532:nonroot:/home/nonroot:/sbin/nologin

**Comment by leojonathanoh** [comment]
> It takes quite some time to get the UIDs

I was tripped up by this one, and permissions problems showed up as errors such as `Tunnel credentials file '/root/.cloudflared/c5dc64e5-9b1d-4948-a4f1-6260dbc68954.json' doesn't exist or is not a file
`. But spining up an `alpine` container in place showed the file existed. So the application showed a wrong error message that was confusing. One should not assume that users would bother to look into the original `Dockerfile` to find out how the base image was built.

In general, many docker images are not built with `USER` because of hiccups it will cause for a new user of the image. A simple `docker run` command should work out of the box in most cases. In my opinion locking down permissions should not be done in the docker image, but as part of deployment, e.g. CD manifests etc. Hence it would be great if the base image did not lock the `USER` to `nonroot`.

**Comment by dahu33** [comment]
Where is this documented?

**Comment by gertvdijk** [comment]
Also unable to find this listed in docs. Could be found in source here, though:

https://github.com/GoogleContainerTools/distroless/blob/859eeea1f9b3b7d59bdcd7e24a977f721e4a406c/base/base.bzl#L8

https://github.com/GoogleContainerTools/distroless/blob/859eeea1f9b3b7d59bdcd7e24a977f721e4a406c/base/BUILD#L9
