### ISSUE TITLE
Add option in cacerts rules to include additional ca certs

### ISSUE THREAD

**Issue by mariusgrigoriu** [GoogleContainerTools/distroless#451]
It would be very useful if it were easier to add custom ca certs. PR #272 aims to do that.

**Comment by mabrarov** [comment]
Hmm... I always thought that CA certs are part of configuration, so they should not be configured and image level (I mean #272) but should be provided at runtime (at least additional CA certs). In case of plain Docker it will be file(s) / directory mounted from docker host, in case of K8s or OpenShift it will be a volume which can be prepared / populated by init container which uses another volume filled from template parameter where CA certs can be stored in the form of single CA bundle, so that init container just splits that CA bundle into multiple files.

Doesn't this approach work for Debian (libssl)?

**Comment by mabrarov** [comment]
Just in case if smbd is interested in the way CA certificates can be added into Java application utilizing Distroless Java image at runtime using init container (i.e. Java trust store generation is performed by init container) - take a look at [docker-compose-init-container](https://github.com/mabrarov/docker-compose-init-container) example.
