### ISSUE TITLE
Support for versions above openjdk11 in distroless

### ISSUE THREAD

**Issue by kunal-bhatia** [GoogleContainerTools/distroless#459]
Hi, any plans and/or roadmap for supporting versions **above openjdk11** in the distroless image for Java?

Thanks!

**Comment by chanseokoh** [comment]
Most likely Java 17 (LTS) will make into it (hopefully). But I don't think we will see anything below 17. No general roadmap I am aware of, sorry.

**Comment by therealppa** [comment]
Any hint where to start if I want to build my own distroless image base on e.g. Java 13 or 14?

**Comment by chanseokoh** [comment]
Distroless set up the infrastructure to get Debian packages. I see `openjdk-13-jre-headless` is in the Bullseye "testing" channel that is being prepared for the next Debian 11 release. I quickly hacked the repo to unpack `openjdk-13-jre-headless` on top of the current Debian 10 images, but as I feared, it doesn't run due to GLIBC package incompatibility.
```
$ docker run --rm bazel/java:java13_debian10_jre13_from_bullseye_testing
Error: dl failure on line 603
Error: failed /usr/lib/jvm/java-13-openjdk-amd64/lib/server/libjvm.so, because /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/jvm/java-13-openjdk-amd64/lib/server/libjvm.so)
```
Even if it didn't crash, there would always be potential incompatibility issues, so you should really use Bullseye packages for everything. Note Bullseye isn't released (may be released in 2021?), so the best channel for these packages is the "testing" channel, which may constantly change until Bullseye is released.

In any case, I expect adding Bullseye packages in Distroless will not be difficult, thanks to the established infrastructure in the Distroless repo. In a nutshell, I think it amounts to
- define `dpkg_src(...)` rules in `WORKSPACE` to declare Bullseye channels you want to use. See `WORKSPACE` for existing examples for Stretch (Debian 9) and Buster (Debian 10).
- define `dpkg_list(...)` with the channels you defined above to articulate all the `.deb` packages you ever want to use. See `WORKSPACE` for existing examples.
- define `container_image` in `java/BUILD` and list the packages you want to unpack. See existing rules in `java/BUILD` as an example. You'll find that you also need to update `cc/BUILD`, as `java/BUILD` depends on it. Then, I believe `cc/BUILD` in turn depends on `base/BUILD`, so most likely you'll need to update `base/BUILD` too. There may be more?
- `bazel run  --host_force_python=PY2 //java:<your container_image rule name>` will build and push an image to your local Docker daemon.

**Comment by therealppa** [comment]
Thank you very much for the detailed description :)

**Comment by nameisnotempty** [comment]
@therealppa Were you able to get this running? If so, could you please share the changes you have done?

**Comment by therealppa** [comment]
> @therealppa Were you able to get this running? If so, could you please share the changes you have done?

Unfortunately I could not commit the time to do this. I ended up using a non-distroless base image for Java 14.

**Comment by therealppa** [comment]
I think the industry is slowly waking up to the conclusion that so called "LTS" versions are not the best version to use, especially if you don't pay for a commercial LTS service. I'm not super sure what the state of Java 11 in debian is, but I worry that it's not getting the same attention as "mainline" OpenJDK, whis is by now on version 14 with 15 around the corner. Some security patches might be backported but I'm pretty confident that current Java is more secure than OpenJDK 11.

Is there any thought to revisit the policy of the distroless project to only consider "LTS versions"?

**Comment by chanseokoh** [comment]
LTS versions may not be the best versions to use for some people, I agree. However, I am pretty sure the Debian folks (and any other Linux distro vendors packaging OpenJDK 11) put the same attention to as the attention to what you call "mainline" OpenJDK for security patches on their stable release. I'm sure it applies to any other entities providing their own builds of "LTS" OpenJDK, such as AdoptOpenJDK, Azul, Red Hat, Amazon, Alibaba, etc. You could claim that these vendors and builders may not pay the same attention to OpenJDK 11 as they would do to non-LTS versions regarding security patches, but I don't really see the evidence. As soon as they don't, they should drop the claim that they fully support OpenJDK 11 as their roadmap. So far, Debian has been taking care of JDK security vulnerabilities in a timely manner. A lot of people are watching them.

**Comment by reneleonhardt** [comment]
LTS JDK 17 is officially 9 days away (the RC is already labeled GA), are there efforts underway to offer a distroless version?

**Comment by leonbreedt** [comment]
GA!

**Comment by kunal-bhatia** [comment]
any update on when will java 17 be available as part of distroless?

**Comment by gabrieljones** [comment]
Is this a dupe of #838?
