### ISSUE TITLE
distroless:java-debian10 not using latest OpenJDK 11 release

### ISSUE THREAD

**Issue by stuartgunter** [GoogleContainerTools/distroless#467]
Hello

I've just pulled the newly-released `distroless:java-debian10` image (thanks @chanseokoh for making this happen!) and noticed that it's running `openjdk 11.0.5 2019-10-15`.

The [latest OpenJDK 11 release](https://packages.debian.org/buster/openjdk-11-jre-headless) for Buster appears to be `11.0.6+10-1~deb10u1`.

I assumed this was specified somewhere in the build, but can't find any reference to it. Unfortunately that means I'm not sure how to help fix this.

Please could we update this to use the latest OpenJDK release? I'm happy to help make this change if someone can direct me to the right place in the repo.

Thanks

**Comment by gertvdijk** [comment]
> Please could we update this to use the latest OpenJDK release? I'm happy to help make this change if someone can direct me to the right place in the repo.

In WORKSPACE, you see it points to a specific Debian repository archive **snapshot**. At that snapshot, the version of OpenJDK was the older one. This is a snapshot to ensure reproducible builds of the image.

In order to update the OpenJDK version, we need to have a reason, like security fixes. This seems to be the case, so we should indeed update the version.

To find the latest snapshot version, have a look at https://snapshot.debian.org/archive/debian/ & https://snapshot.debian.org/archive/debian-security/ . Then update the URLs and SHA256 checksum of the Packages.gz file at that location.

Does that help? Please let me know if you need any help or else I can create this PR and you can see what I did. :)

**Comment by chanseokoh** [comment]
@stuartgunter @gertvdijk filed #470.

**Comment by stuartgunter** [comment]
Thanks @chanseokoh... that was fast! I had made those changes locally, but was struggling to test due to issues with Python on macOS (same as https://github.com/GoogleContainerTools/distroless/issues/434#issuecomment-569289775).

It's good to see the PR so I know how to help out next time (and it confirms I was on the right track after @gertvdijk's pointers) - although I'll probably need to setup a Linux VM to test on if the Python issues persist.

**Comment by chanseokoh** [comment]
@stuartgunter 
see httpss://github.com/GoogleContainerTools/distroless/issues/475 for the certificate workaround.

I expect the new 11.0.6 and 8u242 images will go live within an hour or two.
