### ISSUE TITLE
Having distroless image tags reference specific distros is confusing

### ISSUE THREAD

**Issue by dincciftci** [GoogleContainerTools/distroless#525]
Hi,

Per the README:

> Originally these images were based on Debian 9 (stretch). We now also provide images based on Debian 10 (buster), and tag images with -debian9 or -debian10 suffixes. We recommend referencing the appropriate distribution explicitly, since otherwise your build will break when the next Debian version is released.

It is rather confusing that when one wants to use a "distroless" container, the recommendation is to reference a specific Linux distribution. It is additionally confusing that one needs to pick between two different versions of the said distribution-- one would assume that folks are trying to use a distroless image precisely because they are not interested in the underlying distro.

Suggestions:
1. Deprecate image names that reference debian. Replace with a naming choice that is more meaningful to those consuming the image. (E.g. "legacy", "oldstable", "lts", etc)
2. Document why and how one should pick images based on one release of debian or another. (Why should someone choose to go with the debian 9 based images vs debian 10?)

**Comment by chanseokoh** [comment]
If I recall, the history is that, a brave external contributor showed up and set up an experimental Debian 10 prototype, did all the dirty work, and went on to [publishing `-debian10` images](https://github.com/GoogleContainerTools/distroless/pull/404) as a separate image repo as a precaution and preparation. Then it just happened. I think it sounded like a reasonable choice, maybe because they didn't want to touch the the default live Debian 9 repo that only had the `latest` and `debug` tags? It certainly feels a bit weird to have `:debian9`, `:debian10`, and `:latest`, while `:latest` pointing to `:debian9`.

But I agree this can be confusing. But I don't know either what's the best option going forward.

> Document why and how one should pick images based on one release of debian or another. (Why should someone choose to go with the debian 9 based images vs debian 10?)

I think one should always aim for using the most latest and up-to-date versions. (That is, Debian 10 as of now.)

**Comment by petermylemans** [comment]
Personally I would agree with this sentiment and dropping the -debian10 suffixes. There are plenty of alternatives already available that allow you to build containers distro-style by pulling in additional packages etc... I'm a JVM guy (mostly) and what I see 90% of the time is teams building "custom" fat containers that do "run my jar". There is definitely a place for a project that tries to focus on this type of use case.

The advantage of keeping debian 9 and debian 10 **internally** would be for clarity in the code for people maintaining the stacks. Buster also seems to have dropped java 8 packaging, so there you are stuck with using debian 9 at the moment. But that alone should be no reason to leak these details through the image tags. 

The added value of this project - to me and as I understand it - is to have minimal images focusing on the latest supported version(s) of the underlying software stack and its minimal set of runtime dependencies. The only differentiation to be done should be at the level of versions of the software stack: java 8 vs java 11, node 10 vs node 12 ...
