### ISSUE TITLE
All NodeJS module files have the execute bit set

### ISSUE THREAD

**Issue by Cerebus** [GoogleContainerTools/distroless#546]
```
container=`buildah from gcr.io/distroless/nodejs:latest`
mnt=`buildah mount $container`
find $mnt -type f -executable | wc -l
buildah umount $container
```
I get 4201 files set +x, with stuff like:
```
./nodejs/CHANGELOG.md
./nodejs/LICENSE
./nodejs/README.md
./nodejs/bin/node
./nodejs/bin/npm
./nodejs/bin/npx
./nodejs/include/node/common.gypi
./nodejs/include/node/config.gypi
./nodejs/include/node/libplatform/libplatform-export.h
./nodejs/include/node/libplatform/libplatform.h
./nodejs/include/node/libplatform/v8-tracing.h
```
This is probably Not What You Want.  :)

**Comment by chanseokoh** [comment]
I think this is because [`pkg_tar`](https://github.com/GoogleContainerTools/distroless/blob/d18527663d8aaa193e4cd9db186ff79b2269a314/experimental/nodejs/BUILD.nodejs#L5) to create a tarball has `0555` as the default permissions for the `mode` attribute:
- https://docs.bazel.build/versions/master/be/pkg.html#pkg_tar
- https://github.com/bazelbuild/rules_pkg/tree/master/pkg#pkg_tar

Potentially one could manually list which files are executable and which are not with `modes`, which may work if there are only a handful of executable binaries. Another way would be to have multiple `pkg_tar` rules each of which uses different glob and `exclude` patterns, but this still requires manually identifying and classifying executable vs non-executable files. Might work nicely if `/nodejs/bin/` is the only directory for executable binaries.

(BTW, although I frequently spend some of my spare time on this repo, I certainly don't have any bandwidth or interest in resolving issue myself.)
