### ISSUE TITLE
Add `/bin/kill` so distroless works with TektonCD/Argo Workflows

### ISSUE THREAD

**Issue by alexec** [GoogleContainerTools/distroless#724]
Kubernetes does not provide a mechanism to kill a specific container within a pod, the only options are:

1. Run `kubectl exec my-pod -c my-ctr -- /bin/kill 1`. Works for some shell-less containers.
2. Run `kubectl exec my-pod -c my-ctr -- /bin/sh -c 'kill 1'`. Works for most containers.
3. Run `kubectl delete pod my-pod`. Deletes the pod - which we don't want.

Distroless containers are becoming more popular, e.g. used within ISTIO. But we cannot kill them, as none of the above options work.

I'm open to options.

**Comment by mabrarov** [comment]
Hi,

`kill` utility can be added with BusyBox on top of existing Distroless images, can't it?

Feel free to check [mabrarov/docker-compose-init-container](https://github.com/mabrarov/docker-compose-init-container) where BusyBox is added into `abrarov/docker-compose-init-container-initializer` image (and then "installed" by [creating symlinks](https://github.com/mabrarov/docker-compose-init-container/blob/master/init-image/src/main/resources/Dockerfile#L7)) and that includes `kill` utility:

```
$ docker run --rm abrarov/docker-compose-init-container-initializer kill --help
BusyBox v1.31.0 (2019-06-10 15:54:54 CEST) multi-call binary.

Usage: kill [-l] [-SIG] PID...

Send a signal (default: TERM) to given PIDs

        -l      List all signal names and numbers
```

I'm not ensured how hard is to add BusyBox (or some other binary) into particular image based on Distroless - it may depend on the build system (it's not hard with Maven and Docker Maven Plugin in my case) - but it doesn't look like `kill` needs to be included into Distroless images by default.

**Comment by alexec** [comment]
You solution works if you either have full control over the image building, or the pod manifest (you could have an unit container mount the kill binary). Unfortunately, neither of these are true for a container injected by a mutating webhook. For example, ISTIO or Vault. Both of these are common place. It also doesn’t scale, as it requires every single build pipeline to be updated to add the binary.

**Comment by mabrarov** [comment]
> For example, ISTIO or Vault.

Doesn't it mean that Istio and Vault projects should change their images for injected containers (instead of using plain Distroless)?

**Comment by alexec** [comment]
Again, that's a scalability problem. I now need to open N issues with N projects, and only one needs to reject it to undermine the solution. Better to fix in one place.

**Comment by mabrarov** [comment]
I'm sorry for spamming this feature request and I promise this is my last stupid reply :) Here are some thoughts that I'd like to have a feedback for:

1. Asking an image (container) to carry a binary just to make an orchestration / CD environment able to stop container by sending a signal to the container's process seems to be wrong direction. Sending signals to container's process looks like responsibility of K8s / OpenShift or container engine (Docker, CRI-O, etc.) and `kubectl exec my-pod -c my-ctr -- /bin/kill 1` looks like a workaround, not a solution.
1. I can understand the reason `kubectl` doesn't provide ability to stop particular container of pod - because it's pod and not container who is the unit managed by `kubectl` (by K8s). But `kubectl attach`, `kubectl exec` and `kubectl logs` provide ability to choose container within pod. Why can't we have `kubectl stop` or `kubectl signal` with ability to stop / send signal to particular container of pod then? Should we ask K8s for adding this feature instead of relying on container image to contain a binary able to send signal to the process?
1. As for CD tool (like ArgoCD) - could it try to step deeper into container engine for stopping container as a workaround (until this feature is implemented at K8s layer)? Both docker client (`docker`) and `crictl` tool provide ability to stop container.

**Comment by alexec** [comment]
>  looks like a workaround, not a solution.

100% correct. 

> Why can't we have kubectl stop or kubectl signal 

That would be great!

`crictl`? I've not heard of this. I will investigate.

**Comment by dlorenc** [comment]
At least for TektonCD, @ImJasonH was working on an idea awhile ago where the CICD environment would be able to inject utilities like this into a container.

**Comment by ImJasonH** [comment]
Hey @alexec 👋 

I agree that this problem is real, but that it probably doesn't mean that `distroless` should include `/bin/kill`, or that it should be assumed to exist in all/most/any images.

The challenge is real because you (presumably, and so does Tekton) want to be able to run any arbitrary container image the user brings, and be able to reliably control its lifecycle. Tekton solves the first part by injecting the `entrypoint` binary (see [KubeCon talk](https://www.youtube.com/watch?v=iz9_omZ0ctk) on this) in an init container. Since that talk we actually improved it even more by having the entrypoint binary copy _itself_ to a shared volume mounted to all steps, which enables more multi-arch options (see https://github.com/tektoncd/pipeline/pull/3286)

To stop containers today (e.g., timeout, cancellation), Tekton simply deletes the pod, though we'd like to improve that too (see https://github.com/tektoncd/pipeline/issues/3238)

To extend this to include stopping containers, we could either build and inject a `kill` binary like we do with the entrypoint, or since we already have the entrypoint, we could have it control the end of the lifecycle of the user's command as well as the beginning, perhaps by looking for a `/tekton/tools/kill` file backed by downward API (we use a similar approach to keep the first step from starting until all sidecars report as Ready).

If you're doing something along the lines of Tekton's `entrypoint`, you'll probably also have a better time having it manage stopping the user's command, and if not, you can inject a `kill` binary to a shared mounted volume across all your containers and call that (via `kubectl exec`, etc.)

This response got kind of long and into details, but the tl;dr is that I think we have enough options available to us (in Tekton at least, and I think in Argo) to solve this without building things into distroless. Doing that would increase the size and attack surface of distroless unnecessarily, and not help users who bring images based on other base images (even `scratch`!).

In a dream world, K8s would have more features for declaring the lifecycle of containers in a Pod ("start this after this finishes", "start this but fail after 10m", some standard API to stop containers or pods from outside without deleting), and Tekton and Argo wouldn't have to build our own silly hacks. But we work with what we have. 🤷‍♂️

**Comment by alexec** [comment]
@imjasonh you're quite correct - and this is exactly what I've ended up doing for Argo Dataflow. 

The primary benefit of this would be that any containers that are injected (e.g. ISTIO/Vault) and are based on distroless would be easily killable. With that said, I think it would be better for those products to add it during their build, not here, as maybe they use scratch.
