### ISSUE TITLE
when can we expect distroless based on bullseye?

### ISSUE THREAD

**Issue by sambercovici** [GoogleContainerTools/distroless#780]
debian bullseye is expected to be GA on 14th August.
when can we expect to get distroless based on debian 11 (aka. bullseye)

**Comment by loosebazooka** [comment]
We're working on it, but need to update our builds to remove the dependency on snapshot.debian.org (which has been somewhat flaky lately). There's no actual timeline for this except "near future".

**Comment by sambercovici** [comment]
As I needed it now, I have an ugly hacked clone at: https://github.com/sambercovici/distroless

**Comment by loosebazooka** [comment]
I'm a little surprised nothing went wrong. There is no `Packages.gz` in the updates channel for bullseye. Only a `Packages.xz`. Code needs to be updated to handle that. Or it's just silently ignoring the updates channel all together.

https://snapshot.debian.org/archive/debian/20210806T092041Z/dists/bullseye-updates/main/binary-amd64/

**Comment by chanseokoh** [comment]
It's going to be all `.xz` going forward? https://github.com/GoogleContainerTools/distroless/issues/463

**Comment by joshuagl** [comment]
> We're working on it, but need to update our builds to remove the dependency on snapshot.debian.org (which has been somewhat flaky lately). There's no actual timeline for this except "near future".

I'm surprised to read about a move away from snapshot.debian.org, is that documented somewhere? I've [commented before](https://github.com/GoogleContainerTools/distroless/issues/602#issuecomment-720486430) that:

> One of the nice, presumably intended, consequences of distroless using snapshots.debian.org, is that one can recreate a given distroless image even when the main Debian release archives have moved on.

If we switch away from snapshots.debian.org, then we lose the ability to reliably reproduce distroless container images.
That is because package versions which are no longer listed by a package index are reaped from the pool. Package versions stop being listed by the package index when a newer version replaces them.

**Comment by dlorenc** [comment]
> I'm surprised to read about a move away from snapshot.debian.org, is that documented somewhere? I've [commented before](https://github.com/GoogleContainerTools/distroless/issues/602#issuecomment-720486430) that:
> 
> >

Sorry we're keeping the snapshotting, just not relying on that service because it's been very very flaky. @loosebazooka setup a job to copy things from there over to a GCS bucket that we can use directly for builds over here: https://github.com/GoogleContainerTools/distroless/pull/783

**Comment by joshuagl** [comment]
Thanks for the fast reply Dan!

While I understand the logic, that seems a bit of a shame as it reduces the "transparency" of distroless images (harder to map to upstream Debian contents).

Presumably that also makes it harder to build custom distroless images with Bazel which only include the components the Bazel target needs (when those custom images require dependencies not in the gcs cache).

**Comment by dlorenc** [comment]
Yeah, it's really unfortunate. The "flakiness" has pretty much been a showstopper though, we've gone days/weeks without being able to get a single build to complete successfully. 

@loosebazooka and @priyawadhwa are working on some longer term plans to actually build packages from source reproducibly and use those rather than the snapshot binaries directly (and checking the reproduction).

We'd actually like to use the distroless images as a showcase/dogfooding examlpe for SLSA over time, getting everything built from source following all the best practices available.

**Comment by joshuagl** [comment]
At the risk of overloading this issue (please redirect me to a more appropriate place to discuss if one exists) I noticed DebConf 21 included a talk on "[Making use of snapshot.debian.org for fun and profit](https://debconf21.debconf.org/talks/22-making-use-of-snapshotdebianorg-for-fun-and-profit/)" which includes mention of
> a new testing implementation of snapshot service without throttling https://debian.notset.fr/snapshot
