### ISSUE TITLE
python3-debian10 image namedtuple has no attribute '_field_defaults'

### ISSUE THREAD

**Issue by HaloWorld** [GoogleContainerTools/distroless#909]
Hello,

According to [python doc](https://docs.python.org/3.7/library/collections.html#collections.somenamedtuple._field_defaults), the namedtuple class has property `_field_defaults` which is a dictionary mapping field names to default values. But when I tried to access this property inside a distroless image(python3-debian10), the following error shows up:

> AttributeError: 'Account' object has no attribute '_field_defaults' .

After a period of debugging, I found that the attribute `_fields_defaults` does exist, which is weird because `_fields_defaults` is an alternate spelling for backward compatibility and somehow replaces the original `_field_defaults`.

Steps to reproduce this:

Dockerfile

```Dockerfile
FROM python:3-slim AS build-env
COPY . /app
WORKDIR /app

FROM gcr.io/distroless/python3-debian10
COPY --from=build-env /app /app
WORKDIR /app
CMD ["test.py"]
```

test.py

```python
from collections import namedtuple

Account = namedtuple('Account', ['type', 'balance'], defaults=[0])
for attr in ['_fields_defaults', '_field_defaults']:
    print("Get attr: ", attr)
    try:
        print(getattr(Account, attr))
    except AttributeError:
        print("AttributeError: ", attr)
    print("-" * 42)
```

then execute

```
docker build . t foo && docker run --rm foo
```

Expect result:

```
Get attr:  _fields_defaults
AttributeError:  _fields_defaults
------------------------------------------
Get attr:  _field_defaults
{'balance': 0}
------------------------------------------
```

Actual result:

```
Get attr:  _fields_defaults
{'balance': 0}
------------------------------------------
Get attr:  _field_defaults
AttributeError:  _field_defaults
------------------------------------------
```

**Comment by loosebazooka** [comment]
Hrmm.. @evanj any ideas about this python stuff?

**Comment by evanj** [comment]
This is expected: Distroless ships the exact same Python as Debian, and we get the same results. Debian 10 (Buster) ships Python 3.7. That version shipped with the name `_fields_default` in the namedtuple module by mistake. See the upstream Python bug for details: https://bugs.python.org/issue36321 . I get the same result with this test program if I use the `debian:10` base image instead of `gcr.io/distroless/python3-debian10`. The solution is to use the latest version of Debian by using `gcr.io/distroless/python3-debian11` as the base image, which ships Python 3.9.2, which corrects this misspelling.

To be specific, I used this `Dockerfile`:

```
FROM debian:10
COPY * /app/
RUN apt-get update && apt-get install python3-minimal --yes
WORKDIR /app
ENTRYPOINT ["python3"]
CMD ["test.py"]
```

And get this result:

```
Get attr:  _fields_defaults
{'balance': 0}
------------------------------------------
Get attr:  _field_defaults
AttributeError:  _field_defaults
------------------------------------------
```

**Comment by HaloWorld** [comment]
Thank you for the detailed information. After a period of consideration, we chose to migrate our code to python3.9, and now everything is normal. Great job btw.
