### ISSUE TITLE
Why is the term "Docker" so often in the README?

### ISSUE THREAD

**Issue by guettli** [GoogleContainerTools/distroless#945]
Why is the term "Docker" so often in the README?

AFAIK K8s does not depend on Docker any more.

**Comment by loosebazooka** [comment]
Probably gonna need some quotes or links to what you mean.

**Comment by ericofusco** [comment]
@guettli might be referencing the [dockershm deprecation](https://kubernetes.io/blog/2020/12/02/dockershim-faq/) in k8s?

I don't think distroless has or should have a direct relation or dependency on k8s but I agree with his thought.

Because Docker's popularity it used to be used with the term "container" interchangeably quite often, nowadays with the popularity of tools and standards around containers, I believe the more broad term "container" is best suited. For example instead of calling `"Distroless" Docker Images` I'd simply use `"Distroless" Container Images`.
